title: Geoflow UI
lang: en
auth: false
auth_type: ocs
auth_url: http://localhost:8080
auth_timeout: 0
auth_background: "linear-gradient(rgba(0, 140, 142, 0.9), rgba(255, 255, 255, 0.5))"
auth_header: "<h2>Geoflow</h2>"
auth_footer: "<p>Geoflow UI</p>"
data_dir_local: .
data_dir_remote: geoflow
logger: INFO
